version: '3.8'

services:
  weather-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DEVELOPMENT_MODE=true
      - MOCK_GCS=true
      - GCS_BUCKET_NAME=weather-data-bucket-local
    volumes:
      - ./:/app  # For development - mount current directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 